# Generated by Django 4.2.5 on 2023-09-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtracked',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mail.destinatario'),
        ),
    ]
