# Generated by Django 4.2.5 on 2023-09-21 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_emailtracked_dest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtracked',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='emailtracked',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailtracked',
            name='sent_try',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
